# Generated by Django 5.2 on 2025-05-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postzy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
