# Generated by Django 5.2 on 2025-05-27 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postzy', '0002_customuser_is_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Enter a Valid 10 Digit Phone Number')]),
        ),
    ]
